property-level: 'portal dev level'
security:
  oauth2:
    resource:
      token-info-uri: http://localhost:8185/oauth/check_token
    client:
      client-id: mobile
      client-secret: pin
spring:
  datasource:
    url: jdbc:mysql://sis-db.ceggfqkkv7i5.us-east-1.rds.amazonaws.com:3306/portalDB?createDatabaseIfNotExist=true
    username: sis_root
    password: SisTester123$
    driver-class-name: com.mysql.jdbc.Driver