property-level: 'portal dev level'
security:
  oauth2:
    resource:
      token-info-uri: http://localhost:8185/oauth/check_token
    client:
      client-id: mobile
      client-secret: pin
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/portalDB?createDatabaseIfNotExist=true
    username: root
    password: 1qaz2wsx3edc4rfv!QAZ@WSX#EDC$RFV
    driver-class-name: com.mysql.jdbc.Driver