property-level: 'portal dev level'

spring:
  datasource:
    url: jdbc:mysql://sis-db-cluster.ceggfqkkv7i5.us-east-1.rds.amazonaws.com:3306/customer?createDatabaseIfNotExist=true
    username: sis_root
    password: SisTester123$
    driver-class-name: com.mysql.jdbc.Driver
  security:
    oauth2:
      resource:
        token-info-uri: http://localhost:8185/oauth/check_token
      client:
        client-id: mobile
        client-secret: pin