property-level: 'auth dev level'
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth?createDatabaseIfNotExist=true
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
