property-level: 'auth dev level'
spring:
  datasource:
    url: jdbc:mysql://sis-db.ceggfqkkv7i5.us-east-1.rds.amazonaws.com:3306/auth?createDatabaseIfNotExist=true
    username: sis_root
    password: SisTester123$
    driver-class-name: com.mysql.cj.jdbc.Driver
management:
  endpoints:
    web:
      cors:
        allowed-origins: http://ec2-3-235-104-89.compute-1.amazonaws.com:8182
